window.loadingMessages = [
    { text: "Negotiating with stubborn metadata…", tags: [] },
    { text: "Knapping raw data into usable shapes…", tags: [] },
    { text: "Sifting through layers of metadata…", tags: [] },
    { text: "Harvesting stable chunks…", tags: [] },
    { text: "Generating chunks…", tags: [] },
    { text: "Loading entities into their coordinates…", tags: [] },
    { text: "Teaching the archive how to remember…", tags: [] },
    { text: "Waking the dormant pixels one by one…", tags: [] },
    { text: "Reconciling the gallery’s fractured chronology…", tags: [] },
    { text: "Negotiating peace between timestamps…", tags: [] },
    { text: "Tempering thumbnails…", tags: [] },
    { text: "Resolving biomes of information…", tags: [] },
    { text: "Spawning entities…", tags: [] },
    { text: "Parsing raw HTML into coherent shapes…", tags: [] },
    { text: "Mapping each item to its destined position…", tags: [] },
    { text: "Guiding each image toward its rightful star…", tags: [] },
    { text: "Persuading the data to line up…", tags: [] },
    { text: "Rebuilding item structures with a steady hand…", tags: [] },
    { text: "Letting the index map settle into alignment…", tags: [] },
    { text: "Letting the gallery sprout…", tags: [] },
    { text: "Letting each image choose its favorite spot…", tags: [] },
    { text: "Letting the timeline unfurl…", tags: [] },
    { text: "Placing blocks where the world requested them…", tags: [] },
    { text: "Resolving coordinates…", tags: [] },
    { text: "Filling in the fog‑of‑war…", tags: [] },
    { text: "Tracing the pathways between scattered data…", tags: [] },
    { text: "Tracing the outline of the gallery…", tags: [] },
    { text: "Letting the world load…", tags: [] },
    { text: "Placing structural elements…", tags: [] },
    { text: "Creating the gallery’s scaffolding…", tags: [] },
    { text: "Reconstructing order…", tags: [] },
    { text: "Pressing layers into a workable foundation…", tags: [] },
    { text: "Stabilizing terrain…", tags: [] },
    { text: "Letting the world assemble…", tags: [] },
    { text: "Guiding towards final coherence…", tags: [] },
    { text: "Reinforcing foundations…", tags: [] },
    { text: "Restoring temporal continuity…", tags: [] },
    { text: "Indexing forgotten moments…", tags: [] },
    { text: "Indexing dormant memories…", tags: [] },
    { text: "Whispering instructions to the cache…", tags: [] },
    { text: "Balancing data constellations…", tags: [] },
    { text: "Encouraging coherence…", tags: [] },
    { text: "Awaiting structural convergence…", tags: [] },
    { text: "Hydrating entities…", tags: [] },
    { text: "Compiling structural intent…", tags: [] },
    { text: "Consolidating reference maps…", tags: [] },
    { text: "Letting the gallery bloom…", tags: [] },
    { text: "Waiting for alignment to flower…", tags: [] },
    { text: "Indexing what the internet forgot…", tags: [] },
    { text: "Rescuing images from algorithmic oblivion…", tags: [] },
    { text: "Letting abandoned frames be seen again…", tags: [] },
    { text: "Sorting the unsorted…", tags: [] },
    { text: "Reconciling modtimes with memory…", tags: [] },
    { text: "Sorting through a digital continent…", tags: [] },
    { text: "Auditing a digital continent…", tags: [] },
    { text: "Stabilizing a city of images…", tags: [] },
    { text: "Reconciling a civilization of frames…", tags: [] },
    { text: "User persistence detected…", tags: [] },
    { text: "Generating distant terrain…", tags: [] },
    { text: "Populating empty coordinates…", tags: [] },
    { text: "Simulating permanence…", tags: [] },
    { text: "Cataloging without complaint…", tags: [] },
    { text: "Safeguarding small histories…", tags: [] },
    { text: "Saving… Do not turn off the power.", tags: [] },
    { text: "Synchronizing data…", tags: [] },
    { text: "Please wait…", tags: [] },
    { text: "Processing…", tags: [] },
    { text: "Building cache…", tags: [] },
    { text: "Preparing environment…", tags: [] },
    { text: "Completing setup…", tags: [] },
    { text: "Sorting between comeback eras…", tags: [] },
    { text: "Mapping eras to memory…", tags: [] },
    { text: "Indexing across eras…", tags: [] },
    { text: "Another era preserved.", tags: [] },
    { text: "Synchronizing eras…", tags: [] },
    { text: "Tracking the arc of a career…", tags: [] },
    { text: "Preserving moments between schedules…", tags: [] },
    { text: "Organizing lightsticks in the distance…", tags: [] },
    { text: "Indexing lightstick oceans…", tags: [] },
    { text: "Another comeback preserved.", tags: [] },
    { text: "Retention level: extreme.", tags: ["upgrade"] },
    { text: "Stay.", tags: ["mid"] },
    { text: "Compiling index…", tags: [] },
    { text: "Staging environment…", tags: [] },
    { text: "Background tasks in progress…", tags: [] },
    { text: "Almost there.", tags: [] },
    { text: "Tracking changes…", tags: [] },
    { text: "Rehydrating unloaded regions…", tags: [] },
    { text: "Building spawn logic…", tags: [] },
    { text: "Initializing world state…", tags: [] },
    { text: "Maintaining world persistence…", tags: [] },
    { text: "Spawn set.", tags: [] },
    { text: "You remember what year that was?", tags: ["mid"] },
    { text: "Autosaving…", tags: [] },
    { text: "Quest log updated.", tags: ["upgrade"] },
    { text: "Fast travel unavailable.", tags: [] },
    { text: "Memory shard acquired.", tags: ["upgrade"] },
    { text: "Archive level increased.", tags: ["upgrade"] },
    { text: "Persistence stat boosted.", tags: ["upgrade"] },
    { text: "Continue?", tags: [] },
    { text: "Mapping fanmeeting smiles…", tags: [] },
    { text: "Metadata skill upgraded.", tags: ["upgrade"] },
    { text: "Chronology stabilized.", tags: [] },
    { text: "Sorting speed increased.", tags: ["upgrade"] },
    { text: "Yes, even that blurry one.", tags: [] },
    { text: "Preparing viewing session…", tags: [] },
    { text: "Reconstructing world instance…", tags: [] },
    { text: "Loading character models…", tags: [] },
    { text: "Loading…", tags: [] },
    { text: "Stand by.", tags: [] },
    { text: "Indexing music show rotations…", tags: [] },
    { text: "You looking for something specific?", tags: ["mid"] },
    { text: "Take your time.", tags: ["mid"] },
    { text: "Extending render distance…", tags: [] },
    { text: "Cameras flashing…", tags: [] },
    { text: "This moment was live once.", tags: ["mid"] },
    { text: "You’ve opened this one before.", tags: ["mid"] },
    { text: "Yes, even the low-res preview.", tags: [] },
    { text: "Yes, even the watermark version.", tags: [] },
    { text: "Is this the best angle?", tags: ["mid"] },
    { text: "Take your time?", tags: ["mid"] },
    { text: "How long ago was this?", tags: ["mid"] },
    { text: "You remember how different things were?", tags: ["mid"] },
    { text: "Good thing this did?", tags: ["mid"] },
    { text: "Deduplicating at sub-pixel precision…", tags: [] },
    { text: "Filtering out reposters…", tags: [] },
    { text: "No, not the repost.", tags: [] },
    { text: "That watermark wasn’t first.", tags: [] },
    { text: "Identifying peak {member} era…", tags: [] },
    { text: "Analyzing {member}'s expression variance…", tags: [] },
    { text: "Prime {member}.", tags: [] },
    { text: "Legendary {member} detected.", tags: [] },
    { text: "You looking for that one {member} photo?", tags: ["mid"] },
    { text: "{member} nostalgia stat increased.", tags: ["upgrade"] },
    { text: "Archive affinity with {member} increased.", tags: ["upgrade"] },
    { text: "{member}.", tags: ["rare","example"] },
    { text: "Similarity score: 99.9%.", tags: [] },
    { text: "No one else was going to remember all of this.", tags: ["rare","example"] },
    { text: "Most of this would be gone by now.", tags: ["rare","example"] },
    { text: "You don’t have to keep doing this.", tags: ["rare","example"] },
    { text: "Re-indexing memories…", tags: [] },
    { text: "Compacting redundant history…", tags: [] },
    { text: "Verifying source integrity…", tags: [] },
    { text: "Refining thumbnail fidelity…", tags: [] },
    { text: "Measuring nostalgia density…", tags: [] },
    { text: "Confirming this was worth saving…", tags: [] },
    { text: "Reassembling a career…", tags: [] },
    { text: "Soft-locking nostalgia…", tags: [] },
    { text: "Stabilizing obsession parameters…", tags: [] },
    { text: "Mapping lightstick ocean density…", tags: [] },
    { text: "Calculating bias wreck probability…", tags: [] },
    { text: "Cross-referencing bubble updates…", tags: [] },
    { text: "{member} locked in.", tags: [] },
    { text: "Main slayer identified.", tags: [] },
    { text: "Photocard luck recalculating…", tags: [] },
    { text: "Lightstick battery at 3%.", tags: [] },
    { text: "High-resolution delusion detected.", tags: [] },
    { text: "Enhancing eye sparkle intensity…", tags: [] },
    { text: "Critical hit!", tags: ["upgrade"] },
    { text: "Parasocial firmware updated.", tags: ["upgrade"] },
    { text: "Still not over it.", tags: ["mid"] },
    { text: "Priming intersection observers…", tags: [] },
    { text: "Rebuilding client index…", tags: [] },
    { text: "Hashing pixel clusters for {member}…", tags: [] },
    { text: "Indexing facial micro-expressions…", tags: [] },
    { text: "Measuring {member} aura…", tags: [] },
    { text: "{member} visual stability confirmed.", tags: [] },
    { text: "Recursive scan depth increased…", tags: ["upgrade"] },
    { text: "Compiling {member}.dat…", tags: [] },
    { text: "{member} again?", tags: ["mid"] },
    { text: "The archive adjusted something.", tags: ["mid"] },
    { text: "Is that {member}?", tags: ["mid"] },
    { text: "Rollback aborted.", tags: [] },
    { text: "They can see this, can't they.", tags: ["rare"] },
    { text: "{member} saw that.", tags: ["rare"] },
    { text: "A minor correction was applied.", tags: ["mid"] },
    { text: "A detail has been replaced.", tags: ["mid"] },
    { text: "You noticed that too?", tags: ["mid"] },
    { text: "That selection was expected.", tags: ["mid"] },
    { text: "A softer version replaced it.", tags: ["mid"] },
    { text: "You are looking.", tags: ["mid"] },
    { text: "You returned sooner than expected.", tags: ["mid"] },
    { text: "That choice felt familiar.", tags: ["mid"] },
    { text: "A memory was retained.", tags: ["mid"] },
    { text: "The archive is patient.", tags: [] },
    { text: "You're still here?", tags: ["mid"] },
    { text: "that was different", tags: ["mid"] },
    { text: "{member} remembers you", tags: ["rare"] },
    { text: "s███tate ??? recovered } ░░░ o", tags: ["mid"] },
    { text: "err0r: null // resolved", tags: ["mid"] },
    { text: "th̸i̸s̸ ̸r̸e̸n̸d̸e̸r̸e̸d̸ ̸i̸n̸c̸o̸r̸r̸e̸c̸t̸l̸y̸", tags: ["mid"] },
    { text: "who u callin pinhead?", tags: ["mid"] },
    { text: "6 7", tags: ["rare"] },    
    { text: "Traversing the archives…", tags: [] },
    { text: "The images stir…", tags: ["mid"] },
    { text: "Summoning lost moments…", tags: [] },
    { text: "Retrieving relics from the archive…", tags: [] },
    { text: "Memories are being unearthed…", tags: [] },
    { text: "The gallery is forming…", tags: [] },
    { text: "The collection awakens…", tags: [] },
    { text: "Embers of memory ignite…", tags: [] },
    { text: "A phantom of images approaches…", tags: [] },
    { text: "Illusory wall ahead.", tags: [] },
    { text: "Kindling…", tags: [] },
    { text: "Traversing fog…", tags: [] },
    { text: "Ash gathers…", tags: [] },
    { text: "Embers stir…", tags: [] },
    { text: "The archive stirs…", tags: ["mid"] },
    { text: "Retrieving relics of memory…", tags: [] },
    { text: "Images ahead therefore praise the archive.", tags: [] },
    { text: "Visions of memories…", tags: [] },
    { text: "Collection ahead therefore try patience.", tags: [] },
    { text: "Why is it always loading?", tags: [] },
    { text: "Seek {member}", tags: ["mid"] },
    { text: "Traversing the archives of {member}…", tags: [] },
    { text: "Summoning memories of {member}…", tags: [] },
    { text: "Retrieving relics of {member}…", tags: [] },
    { text: "Echoes of {member} awaken…", tags: [] },
    { text: "Visions of {member}…", tags: [] },
    { text: "{member} ahead.", tags: [] },
    { text: "Praise {member}!", tags: [] },
    { text: "The fog lifts… {member} awaits…", tags: [] },
    { text: "Estus Flask Shard Acquired", tags: ["upgrade"] },
    { text: "Archive Tier Increased", tags: ["upgrade"] },
    { text: "Archive Fragments Recovered", tags: ["upgrade"] },
    { text: "Relics of Memory Obtained", tags: ["upgrade"] },
    { text: "Great Soul Embraced", tags: ["rare"] },
    { text: "Primal Bonfire Lit", tags: ["rare"] },
    { text: "The ember glows", tags: ["mid"] },
    { text: "A faint warmth spreads through the archive…", tags: ["mid"] },
    { text: "The process stirs with heavy intent…", tags: [] },
    { text: "A quiet dread settles over the index…", tags: [] },
    { text: "The archive peers back…", tags: ["mid"] },
    { text: "The veil trembles; something wishes to be seen…", tags: ["mid"] },
    { text: "Resolving spectral references…", tags: [] },
    { text: "Rekindling cache…", tags: [] },
    { text: "A faint silhouette of {member} emerges…", tags: [] },
    { text: "", tags: [] },
    { text: "", tags: [] },
];